### ISSUE TITLE
admin login on live site enabled

### ISSUE THREAD

**Issue by prankymat** [mikelmcdaniel/grade-oven#1]
Hey Mikel, it's me Matthew, your past student in 2C this ~~Spring~~ Winter at Foothill :)

I've noticed that the default username and password (admin/admin) specified in the README can be logged in on the live site at (https://gradeoven.com).

This seems to be a serious issue since anyone will be able to create users and many other admin stuff on the live site with this account. Perhaps you should consider changing your password for admin haha

Anyway just wanted to know I had a lot of fun in your class this ~~Spring~~ Winter! Hope you're having fun at Foothill as well!

**Comment by mikelmcdaniel** [comment]
Thanks Matthew! I changed the password a few hours ago when I saw your original message. I forgot to change it earlier.

I'm going to keep this bug open until I add a feature that either requires the user to set an admin password when the site is first created *or* I add a feature that requires a user to reset their password.

**Comment by prankymat** [comment]
no probs! Glad you've changed the password. This sounds like a good feature indeed, sure worth adding it to prevent server being compromised.

Btw hurray for the legit SSL cert for the live site! No more sketchy website warnings from chrome haha
